### ISSUE TITLE
Scott's Permissions

### ISSUE THREAD

**Issue by EssAreDee** [AdaptiveApplications/carnegie#25]
@ajdrake 
My AWS account for AA doesn't have permissions to create the new ElastiCache/Redis instance. I'm happy to do it if you want to alter my permissions or provide service account credentials.

**Comment by ajdrake** [comment]
Will do

**Comment by ajdrake** [comment]
Check it now, I added elasticache fullaccess

**Comment by EssAreDee** [comment]
Seems to have done the trick. Thanks!
